### ISSUE TITLE
maker Stop Running due to the memory space 

### ISSUE THREAD

**Issue by ohan-Bioinfo** [sujaikumar/assemblage#2]
i have Run maker annotation pipeline and it seems working well, but 500G in my disc not enough t , 
i got an external memory size to accomplish the job ,

my question how i can assign all the output to the external rather than using the local space

**Comment by sujaikumar** [comment]
Hi. If you ran the MAKER command in folder /original/folder, then it will create a maker output folder within that folder (eg: /original/folder/sequences.maker.output)

All you have to do is move that whole folder from /original/folder/ to /new/external/sequences.maker.output

If you now run the same command in /new/external, it will reuse the existing data and carry on where it left off.
