### ISSUE TITLE
Question about annotation

### ISSUE THREAD

**Issue by Tdanis** [sujaikumar/assemblage#3]
Hello, I have got one quicjquestion about second run of annotation. 

Why do you keep est and protein evidence? is it necessary? 
And secondly, why you do not pass the previous gff file  run in the next run  (Re-annotation sector)

Thank you

**Comment by sujaikumar** [comment]
Hi there. This guide was written a long time ago, so the latest versions of MAKER and other tools might be different (I haven't done any genome annotation this way in a while)

To answer your first question - annotations are always better with EST/Protein evidence (whether on the first pass or the second pass). If we just use HMM models, we are only using probabilities, whereas ESTs and Protein evidence provide strong support for intron/exon boundaries, start/stop codons, etc.

Second question: Yes, one could have used the GFF generated in the first pass, but I was more interested in using the HMMs generated in the first pass (which are more probabilistic). The GFF generated in the first pass is most likely wrong on many levels (as it is using more crude HMM models). When given a GFF, MAKER trusts it too much! I would only use a GFF in an annotation run if it was from an existing annotation of the same genome.

Hope that helps?
